### ISSUE TITLE
Trim by default extends to not selected sections, which is not safe

### ISSUE THREAD

**Issue by daoane** [corewall/corelyzer#11]
The trim dialogue is preset on "selected and deeper sections". This is not safe, because the user expects to work with the selection. Thus, "selected section only" should be the default and "selected and deeper sections" an option that is actively chosen by the user. This would prevent the accidental trim of a large number of sections, possibly without the user noticing it. As Corelyzer does not implement an undo-function, such a mistake, if discovered, cannot be reverted. To trim in the opposite direction is not a solution because it will not reverse the action when a maximum/minimum value is encountered by any of the sections. Undo functionality is not available - thus, the default option in the trim dialogue has to be safe: "selected section only".

**Comment by sorghumking** [comment]
Fixed by ca312f6225aed87942b1ab099356911e4671162b
