### ISSUE TITLE
Corelyzer 2.1.0 Mac: To open "Corelyzer.app" you need to install the legacy Java SE 6 runtime

### ISSUE THREAD

**Issue by wfinsinger** [corewall/corelyzer#17]
Hi,

Am trying to install Corelyzer 2.1.0 on a macOS (Catalina 10.15.7) but am repeatedly failing to do so.

When I open the Corelyzer.app, the message "To open 'Corelyzer.app' you need to install the legacy Java SE 6 runtime" appears with a link to the "Download Java for OS X 2017-001" webpage (https://support.apple.com/kb/DL1572?locale=en_US). Unfortunately, this Java version is intended for macOS 10.7 to 10.13...and cannot be installed on my system...

I have the recommended Java Version 8 Update 271 (filesize: 80.75 MB) installed on my system but it seems not sufficient...the same message appears and the Corelyzer.app won't open.

Very best,

walt

**Comment by sorghumking** [comment]
Corelyzer 2.1.0 includes a Java 8 runtime in the app bundle, so it shouldn't be looking for an external runtime.  Another user recently reported this issue, but it automagically resolved itself before we began troubleshooting.

If you're comfortable using the command line (Terminal), can you please try the following steps?

1. Move or copy Corelyzer.app to your Desktop.
2. Open Terminal.
3. `cd Desktop`
4. `cd Corelyzer.app/Contents/MacOS`
5. `./Corelyzer`

There's a chance Corelyzer will launch successfully when invoked this way.  Whether or not it does, can you share the text outputted after step 5?  It may give us a clue as to why it won't launch normally.  Thanks!

**Comment by wfinsinger** [comment]
Dear Brian,

Many thanks for offering your troubleshooting help.

I’ve done as suggested by you, and attach two screenshots.
- After step #5 my Mac says Corelyzer.app cannot be opened because it could malicious software.
- If I open my system Preferences and tell my Mac to open the app anyway I receive the message concerning Java SE 6 runtime…

I also tried to open the app after a fresh Restart…this didn’t help either.

Well, meanwhile I’ll continue working with my older Mac, where everything worked perfectly. This is just to say that there’s nothing urgent. On the other hand I suppose that other Mac users may encounter a similar problem when switching to the new MacOS...

Very best,

	walt
