### ISSUE TITLE
macOS: Corelyzer cannot be launched "because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by leilatarabein** [corewall/corelyzer#28]
Hello,
    I'm using a Macbook with the latest version of MacOS and I am unable to open Corelyzer because "Apple cannot check it for malicious software." I've attached the error message that pops up below when I try to launch the application. This is the case for the two latest versions of Corelyzer. 

<img width="270" alt="Screen Shot 2021-06-24 at 1 16 01 PM" src="https://user-images.githubusercontent.com/86429304/123306167-f0ab5f80-d4ee-11eb-998d-81cfc51eb94e.png">

**Comment by sorghumking** [comment]
I can't speak to the latest version of MacOS, but this is a known issue in earlier versions.  Thankfully, there's a simple workaround.  Right-click the Corelyzer app and choose "Open" from the context menu.  Confirm you want to open Corelyzer when prompted.  This should only happen once; after that, Corelyzer will launch normally.

**Comment by leilatarabein** [comment]
> I can't speak to the latest version of MacOS, but this is a known issue in earlier versions. Thankfully, there's a simple workaround. Right-click the Corelyzer app and choose "Open" from the context menu. Confirm you want to open Corelyzer when prompted. This should only happen once; after that, Corelyzer will launch normally.

Hello, unfortunately with the latest version of MacOS, right-clicking and choosing "open" displays the same error message as I've attached above. Do you know if there's another fix for this issue?

**Comment by sorghumking** [comment]
Can you try the steps described in the "If you want to open an app that hasn’t been notarized or is from an unidentified developer" section [here](https://support.apple.com/en-us/HT202491)?

**Comment by leilatarabein** [comment]
> Can you try the steps described in the "If you want to open an app that hasn’t been notarized or is from an unidentified developer" section [here](https://support.apple.com/en-us/HT202491)?

That fixed the issue! Thank you so much!

**Comment by sorghumking** [comment]
**Very relieved** to hear this worked!
